# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'appTeste' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for appTeste
pod 'OneSignal', '>= 2.5.2', '< 3.0'


  target 'appTesteTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'appTeste-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for appTeste-tvOS

  target 'appTeste-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'OneSignalNotificationServiceExtension' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for OneSignalNotificationServiceExtension

end
